config/routes.rb
OrigenNaku::Application.routes.draw do

  devise_for :users

  resources :feedbacks

  resources :proyects

  get "static_pages/index"

  match "/contacto", to: 'static_pages#contacto', via: 'get'
  match "/xaltipan", to: 'static_pages#xaltipan', via: 'get'
  match "/universitarios", to: 'static_pages#universitarios', via: 'get'
  match "/voluntariado", to: 'static_pages#voluntariado', via: 'get'
  match "/tierradegloria", to: 'static_pages#tierradegloria', via: 'get'
  match "/admin", to: 'static_pages#admin', via: 'get'

  root :to => 'static_pages#index'

  mount Judge::Engine => '/judge'

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :content

  validates :content, :presence => { :message => "Falto tu mensaje, escribenos algo." }

end

app/models/proyect.rb
class Proyect < ActiveRecord::Base
  attr_accessible :description, :photo, :thumb, :title, :subtitle, :back_image, :galeria1, :galeria2, :galeria3, :galeria4
  
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  #def should_generate_new_friendly_id?
 	#new_record?
  #end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :load_tweets


  def load_tweets
    account = "origennaku"
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "MkYi53JY8meo9eKJwOOKfZ0GR"
      config.consumer_secret     = "sx8KYQhSuJQNlGf58wHoWT5XbsjZE1Nk68EsEkpUeH0gGNnAAj"
      config.access_token        = "580490259-9A9jZggowwKvw7H7JuMBPc1QWTFs1mlgQGdslWu9"
      config.access_token_secret = "rZmPaE5VNVyMXxDT1fm6IAXoWsXo9AWAhFXPLe0SEaMF5"
    end
    @twitter_user = account
    @tweet_news = client.user_timeline(@twitter_user, {count: 4})
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedbacks }
    end
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/new
  # GET /feedbacks/new.json
  def new
    @feedback = Feedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedback }
      format.js
    end
  end

  # GET /feedbacks/1/edit
  def edit
    @feedback = Feedback.find(params[:id])
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(params[:feedback])

    respond_to do |format|
      if params[:feedback]
        @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render json: @feedback, status: :created, location: @feedback }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /feedbacks/1
  # PUT /feedbacks/1.json
  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to feedbacks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  # GET /proyects
  # GET /proyects.json
  def index
    @proyects = Proyect.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proyects }
    end
  end

  # GET /proyects/1
  # GET /proyects/1.json
  def show
    @proyect = Proyect.find(params[:id])
    if request.path != proyect_path(@proyect)
      redirect_to @proyect, status: :moved_permanently
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proyect }
    end
  end

  # GET /proyects/new
  # GET /proyects/new.json
  def new
    @proyect = Proyect.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proyect }
    end
  end

  # GET /proyects/1/edit
  def edit
    @proyect = Proyect.find(params[:id])
  end

  # POST /proyects
  # POST /proyects.json
  def create
    @proyect = Proyect.new(params[:proyect])

    respond_to do |format|
      if @proyect.save
        format.html { redirect_to @proyect, notice: 'Proyect was successfully created.' }
        format.json { render json: @proyect, status: :created, location: @proyect }
      else
        format.html { render action: "new" }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proyects/1
  # PUT /proyects/1.json
  def update
    @proyect = Proyect.find(params[:id])

    respond_to do |format|
      if @proyect.update_attributes(params[:proyect])
        format.html { redirect_to @proyect, notice: 'Proyect was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyects/1
  # DELETE /proyects/1.json
  def destroy
    @proyect = Proyect.find(params[:id])
    @proyect.destroy

    respond_to do |format|
      format.html { redirect_to proyects_url }
      format.json { head :no_content }
    end
  end

  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :load_tweets
  require 'twitter'


  def index
  end

  def load_tweets
    account = "origennaku"
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "MkYi53JY8meo9eKJwOOKfZ0GR"
      config.consumer_secret     = "sx8KYQhSuJQNlGf58wHoWT5XbsjZE1Nk68EsEkpUeH0gGNnAAj"
      config.access_token        = "580490259-9A9jZggowwKvw7H7JuMBPc1QWTFs1mlgQGdslWu9"
      config.access_token_secret = "rZmPaE5VNVyMXxDT1fm6IAXoWsXo9AWAhFXPLe0SEaMF5"
    end
    @twitter_user = account
    @tweet_news = client.user_timeline(@twitter_user, {count: 4})
  end

  def contacto
  end

  def xaltipan
  end

  def tierradegloria
  end

  def universitarios
    @feedback = Feedback.new
  end

  def voluntariado
    @feedback = Feedback.new
  end

  def admin
  end
end

app/helpers/application_helper.rb
require 'twitter-text'

module ApplicationHelper
 include Twitter::Autolink
 
  def twitter_text(text)
    text = auto_link(text, target: "_blank")
    text ? text.html_safe : ''
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/feedbacks/_form.html.erb
<%= form_for(@feedback) do |f| %>
  <% if @feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% @feedback.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedbacks/create.js.erb
$('#msg').hide('slow')
$('#mensaje').text('Gracias, pronto nos pondemos en contacto contigo.')

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<h1>Listing feedbacks</h1>

<table>
  <tr>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feedbacks.each do |feedback| %>
  <tr>
    <td><%= feedback.content %></td>
    <td><%= link_to 'Show', feedback %></td>
    <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
    <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/new.html.erb
<h1>New feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @feedback.content %>
</p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>

app/views/layouts/_footer.html.erb
<div style="background-image: url('/assets/sandpaper.png')" class="row">
	<div class="container">
		<footer>
			<div class="col-md-4">
				<h3>Contacto</h3>
				<hr>
				<p><span class="glyphicon glyphicon-flag"></span> Fundación Origen
				Nakú A.C</p>
				<p>Calle Arco del triunfo No. 9744 A, Fraccionamiento Rinconada
					los Arcos, Puebla Mexico. C.P. 72480</p>
				<p><span class="glyphicon glyphicon-earphone"></span> (222) 225 1414</p>
				<p><span class="glyphicon glyphicon-earphone"></span> (222) 302 0429</p>
				<p><span class="glyphicon glyphicon-earphone"></span> (222) 302 0430</p>
				<p><span class="glyphicon glyphicon-envelope"></span><a href="mailto:emilio.macedo@fundacionorigennaku.org"> emilio.macedo@fundacionorigennaku.org</a></p>
				<p><span class="glyphicon glyphicon-envelope"></span><a href="mailto:emilio.macedo@fundacionorigennaku.org"> emilio.macedo@fundacionorigennaku.org</a></p>
				<div style="width:250px"><%= image_tag('http://www.poderpda.com/wp-content/uploads/2012/03/Google-Maps-being-offline-doesnt-mean-being-lost.gif') %></div>
			</div>
	  		
	  		<div class="col-md-4">
	  			<h3>Últimos tweets</h3>
	  			<hr>
	  			<% @tweet_news.each do |tweet| %>
					<div class="col-md-2"><%= image_tag('ftwt.png') %></div>
					<div class="col-md-10">
	  					<p>
	  						<%= link_to tweet.user.screen_name, "https://twitter.com/OrigenNaku", target: "_blank" %>
	  					</p>
	  					<p>	
	  						<%= twitter_text(tweet.text) %> 
	  					</p>
	  				</div>
  				<% end %>
	  		</div>
	  		<div class="col-md-4">
	  			<h3>Síguenos</h3>
	  			<hr>
	  			<div class="row">
		  			<div class="col-md-2"><%= link_to image_tag('http://a5.mzstatic.com/us/r30/Purple/v4/f7/25/73/f725731b-6ddf-c2a2-32a6-3029c3e7225a/mzl.uyyqawdj.png'), "https://www.facebook.com/FundacionOrigenNaku?fref=ts", target: "_blank"  %></div>
		  			<div class="col-md-10">Fundación Origen Nakú</div>
				</div>
				<br>
				<div class="row">
		  			<div class="col-md-2"><%= link_to image_tag('http://www.compra-bitcoins.es/img/twitter-compra-bitcoins.png'), "https://twitter.com/OrigenNaku", target: "_blank"  %></div>
		  			<div class="col-md-10">@OrigenNaku</div>
		  		</div>
		  		<br>
		  		<div class="row">
		  			<div class="col-md-2"><%= link_to image_tag('http://rack.1.mshcdn.com/media/ZgkyMDEzLzA4LzI5Lzg2L3lvdXR1YmVsb2dvLjNmZmMzLmpwZwpwCXRodW1iCTk1MHg1MzQjCmUJanBn/334cf6a5/be5/youtube-logo.jpg'), "https://www.youtube.com/channel/UCbjZOvJhXKosTHTueEqgThg", target: "_blank"  %></div>
		  			<div class="col-md-10">Fundación Origen Nakú</div>
				</div>
	  		</div>
	  		<br>
		</footer>
	</div>
	<br>
</div> 
<div class="row" style="background-color:black">
	<div class="container">
		<div class="col-md-4">
			<p class="lead" style="color:white">Desarrollado por <a style="" href="https://twitter.com/JulioAhuactzin" target="_blank">@JulioAhuactzin</a></p>
		</div>
	</div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Fundacion Origen Naku A.C.", root_path, class: 'navbar-brand', 
      style: "font-family: naku; margin-top:5%; font-size: 3em; color: yellow" %>
    </div>
    <div style="margin-top:1%" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<ul class="nav navbar-nav navbar-right">
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Comunidades amigas<b class="caret"></b></a>
    <ul class="dropdown-menu">
        <li><%= link_to "Xaltipan y Tonalix", xaltipan_path %></li>
        <li><%= link_to "Mision tierra de gloria", tierradegloria_path %></li>
    </ul>
  </li>
	<li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Programas<b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a href="http://fundacionorigen.herokuapp.com/proyects/escuela-del-sol">Escuela del Sol</a></li>
        <li><a href="http://fundacionorigen.herokuapp.com/proyects/comedor-infantil">Comedor infantil</a></li>
        <li><a href="http://fundacionorigen.herokuapp.com/proyects/jornadas-solidarias">Jornadas solidarias</a></li>
        <li><a href="http://fundacionorigen.herokuapp.com/proyects/dia-del-nino">Día del niño</a></li>
		   <!-- <li><a href="#">Mision Tierra de Gloria</a></li>
        <li><a href="#">Travesia Tepeyolotl</a></li> -->
        <li><a href="http://fundacionorigen.herokuapp.com/proyects/manos-hermanas">Manos hermanas</a></li>
        <li><a href="http://fundacionorigen.herokuapp.com/proyects/una-navidad-para-todos">Una navidad para todos</a></li>
      </ul>
    </li>	
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Servicio social y Voluntaríado Internacional<b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Universitarios", universitarios_path %></li>
        <li><%= link_to "Voluntaríado Internacional", voluntariado_path %></li>
      </ul>
    </li>
	<li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">¿Cómo Ayudar?<b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><a href="http://fundacionorigen.herokuapp.com/proyects/programa-de-apadrinamiento">Apadrinamientos</a></li>
        <li>
          <a href="http://fundacionorigen.herokuapp.com/proyects/donativos">Donativos</a>
        </li>
        <li class="divider"></li>
        <li><a href="http://fundacionorigen.herokuapp.com/proyects/tarde-de-postres">Tarde de postres</a></li>
      </ul>
    </li>
	<li><%= link_to 'Contacto', '/contacto'%></li>
</ul>	

<script type="text/javascript">
$(document).ready(function(){
    $('.navbar .dropdown').hover(function() {
        $(this).find('.dropdown-menu').first().stop(true, true).delay(150).slideDown();
    }, function() {
        $(this).find('.dropdown-menu').first().stop(true, true).delay(100).slideUp()
    });
})

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Fundación Origen Nakú A.C." %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Origen Naku" %>">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main style="padding-bottom:0px" role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
       <%= render 'layouts/footer' %>
    </main>

  </body>
</html>

app/views/proyects/_form.html.erb
<%= form_for(@proyect) do |f| %>
  <% if @proyect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proyect.errors.count, "error") %> prohibited this proyect from being saved:</h2>

      <ul>
      <% @proyect.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br />
    <%= f.text_area :subtitle %>
  </div>
  <br>
  <div class="field">
    <%= f.label :back_image %><br />
    <%= f.text_field :back_image %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, class: "col-md-12"  %>
  </div>
  <div class="field">
    <%= f.label :galeria %><br />
    <%= f.text_field :galeria1 %>
  </div>
  <div class="field">
    <%= f.label :galeria %><br />
    <%= f.text_field :galeria2 %>
  </div>
  <div class="field">
    <%= f.label :galeria %><br />
    <%= f.text_field :galeria3 %>
  </div>
  <div class="field">
    <%= f.label :galeria %><br />
    <%= f.text_field :galeria4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proyects/edit.html.erb
<h1>Editing proyect</h1>

<%= render 'form' %>

<%= link_to 'Show', @proyect %> |
<%= link_to 'Back', proyects_path %>

app/views/proyects/index.html.erb
<h1>Listing proyects</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Thumb</th>
    <th>Photo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @proyects.each do |proyect| %>
  <tr>
    <td><%= proyect.title %></td>
    <td><%= proyect.description %></td>
    <td><%= proyect.thumb %></td>
    <td><%= proyect.photo %></td>
    <td><%= link_to 'Show', proyect %></td>
    <td><%= link_to 'Edit', edit_proyect_path(proyect) %></td>
    <td><%= link_to 'Destroy', proyect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Proyect', new_proyect_path %>

app/views/proyects/new.html.erb
<h1>New proyect</h1>

<%= render 'form' %>

<%= link_to 'Back', proyects_path %>

app/views/proyects/show.html.erb
<div style="background-image: url('/assets/<%=@proyect.back_image %>'); 
  background-position: center center;" class="row">
	<div class="col-md-4">

    <%= image_tag('titulo_escuela_sol.png', style: "margin: 12%") %>
		<!--<h1 style="margin-top:13%; color:white" class="naku-font"><%= @proyect.title %></h1>
		<p style="color:white" class="naku-font"><%= @proyect.subtitle %></p> -->

	</div>
</div>
<div class="row">
	<div style="" class="col-md-12">
      <%= image_tag('mitad_logo.png', style: "float:left; opacity: 0.25; margin-top: 3%") %>
    <div class="row">
      <div class="col-md-7">
		    <br>
		    <p style="text-align:justify" class="lead">
		      <%= @proyect.description.html_safe %>
		    </p>
	    </div>
    	<div class="col-md-3">
    	  <br>
         <p style="text-align:center">Da click para ver la imagen:</p>
         <ul class="lightGallery">
          <li data-src="/assets/<%= @proyect.galeria1 %>">
            <img src="/assets/<%= @proyect.galeria1 %>" />
          </li>
          <li data-src="/assets/<%= @proyect.galeria2 %>">
            <img src="/assets/<%= @proyect.galeria2 %>" />
          </li>
          <li data-src="/assets/<%= @proyect.galeria3 %>">
            <img src="/assets/<%= @proyect.galeria3 %>" />
          </li>
          <li data-src="/assets/<%= @proyect.galeria4 %>">
            <img src="/assets/<%= @proyect.galeria4 %>" />
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>
<hr>
<%= render partial: "static_pages/proyect_carousel" %>
<br>

<script type="text/javascript">
  $(document).ready(function() {
    $(".lightGallery").lightGallery();
  });
</script>

app/views/static_pages/_feedback.html.erb
<div style="text-align:justify" class="lead" id="msg">
  <h2>¿Te interesa ser parte de la fundación?</h2>
  <h3>Déjanos un mensaje</h3>
  <%= form_for(Feedback.new,:builder => Judge::FormBuilder, :remote => true) do |f| %>
    <% if @feedback.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

        <ul>
        <% @feedback.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.text_area :content, class: "form-control", rows:"10", :validate => true %>
    </div>
    <div class="field">
      <br>
      <%= f.submit 'Enviar', class:"btn btn-success btn-lg", id: "submit"%>
    </div>
  <% end %>
</div>
<br>
<h2 style="text-align: center; color: rgb(47, 199, 47);" id="mensaje"></h2>
<br>
<script type="text/javascript" charset="utf-8">
$(document).ready(function(){
  $('#submit').on('click', function(){
      judge.validate(document.getElementById('feedback_content'), {
      valid: function(element) {
      element.style.border = '1px solid green';
      },
      invalid: function(element, messages) {
      element.style.border = '1px solid red';
      alert(messages.join(','));
      }
    });

  });
});
</script>

app/views/static_pages/admin.html.erb
<div class="row">
  <div class="container">
    <ul class="nav navbar-nav navbar-right">
  	<% if user_signed_in? %>
  		<li ><%= link_to 'Home', root_path %></li>
  		<li class="dropdown_user">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sesion de <%= current_user.email %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
  			<li><%= link_to 'Editar', edit_user_registration_path %> </li>
  			<li><%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
  	 <% else %>
  		<li><%= link_to 'Regístrate', new_user_registration_path %></li>
  		<li><%= link_to 'Iniciar Sesión', new_user_session_path %></li>
  	 <% end %>
    </ul>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function(){
    $('.dropdown_user').hover(function() {
        $(this).find('.dropdown-menu').first().stop(true, true).delay(150).slideDown();
    }, function() {
        $(this).find('.dropdown-menu').first().stop(true, true).delay(100).slideUp()
    });
})

</script>

app/views/static_pages/tierradegloria.html.erb
<div style="background-image: url('/assets/back_tierra_gloria.jpg');" class="row">
	<div class="container">
		<h1 style="margin-top:5%; color:white" class="featurette-heading">Misión Tierra de Gloria, Puebla</h1>
		<p style="color:white" class="lead">Comunidad rural</p>
	</div>
</div>

<div class="row">
	<div class="container">
		<div class="col-md-7">
			<br>
			<p style="text-align:justify" class="lead">
				<strong>San Agustín Ahuehuetla</strong>, es una comunidad rural a las afueras de la ciudad de Puebla, sus habitantes son en su mayoría pastores y productores de artesanías en palma.<br>
				San Agustín Ahuehuetla es una localidad perteneciente al municipio de Huehuetlán el Grande, en el estado de <strong>Puebla</strong>. Está situada a 1.560 metros de altitud sobre el nivel del Mar.<br>
				Tiene 553 habitantes, 275 (49.73%) son hombres y 278 (50.27%) son mujeres, el 50% de la población es mayor de 18 años.  
			</p>
			<div class="list-group">
			  <a href="#" class="list-group-item list-group-item-success">
			    Programas que desarrollamos
			  </a>
			  <a href="#" class="list-group-item">Escuela del sol</a>
			  <a href="#" class="list-group-item">Comedor infantil</a>
			  <a href="#" class="list-group-item">Jornadas solidarias</a>
			  <a href="#" class="list-group-item">Manos hermanas</a>
			</div>
		</div>
		<div clas="col-md-5">
		</div>
	</div>
</div>